TeamDev-IP/DotNetBrowser-Examples

csharp/JavaScriptBridge.WinForms/App.config, vbnet/JavaScriptBridge.WinForms/App.config
This PR improves the `JavaScriptBridge.WinForms` sample (C# and VB.NET).
=> Improve JavaScriptBridge.WinForms sample

csharp/ContextMenu.WinForms/ContextMenu.WinForms.csproj, csharp/ContextMenu.WinForms/packages.config, vbnet/ContextMenu.WinForms/ContextMenu.WinForms.vbproj, vbnet/ContextMenu.WinForms/packages.config
This PR updates package references in the ContextMenu.WinForms example.
=> Fix packages in example

csharp/KeyboardEventSimulation.WinForms/Form1.cs, csharp/KeyboardEventSimulation.Wpf/MainWindow.xaml.cs, vbnet/KeyboardEventSimulation.WinForms/Form1.vb, vbnet/KeyboardEventSimulation.Wpf/MainWindow.xaml.vb
This PR extends the existing examples to demonstrate keyboard input simulation for non-letter characters.
=> Extend examples to demonstrate simulation of non-letter characters.

csharp/JavaScriptBridge/Program.cs, vbnet/JavaScriptBridge/Program.vb
This PR updates the existing examples to demonstrate properties support introduced in DotNetBrowser 2.3.
=> Update JavaScriptBridge examples to demonstrate properties support.

PasswordSaveSample/MainWindow.xaml.cs, WPF.XPathSample/MainWindow.xaml.cs, WinForms.BrowserContextSample/Form1.cs
This pull request fixes the order of the disposing process and adds it in the necessary place.
=> Improve the order of the disposing process

csharp/DotNetBrowser.Examples.sln, csharp/JavaScriptBridge.Arrays/App.config, csharp/JavaScriptBridge.Arrays/JavaScriptBridge.Arrays.csproj, csharp/JavaScriptBridge.Arrays/JsArray.cs, csharp/JavaScriptBridge.Arrays/Program.cs, csharp/JavaScriptBridge.Arrays/Properties/AssemblyInfo.cs, csharp/JavaScriptBridge.Arrays/packages.config, vbnet/DotNetBrowser.Examples.sln, vbnet/JavaScriptBridge.Arrays/App.config, vbnet/JavaScriptBridge.Arrays/JavaScriptBridge.Arrays.vbproj, vbnet/JavaScriptBridge.Arrays/JsArray.vb, vbnet/JavaScriptBridge.Arrays/My Project/AssemblyInfo.vb, vbnet/JavaScriptBridge.Arrays/Program.vb, vbnet/JavaScriptBridge.Arrays/packages.config
Add examples that demonstrate a possible way to handle JavaScript arrays in .NET.
=> Javascript arrays example

csharp/AjaxResponseIntercept/AjaxResponseIntercept.csproj, csharp/AjaxResponseIntercept/App.config, csharp/AjaxResponseIntercept/HttpRequest.cs, csharp/AjaxResponseIntercept/Program.cs, csharp/AjaxResponseIntercept/Properties/AssemblyInfo.cs, csharp/AjaxResponseIntercept/packages.config, csharp/DotNetBrowser.Examples.sln, vbnet/AjaxResponseIntercept/AjaxResponseIntercept.vbproj, vbnet/AjaxResponseIntercept/App.config, vbnet/AjaxResponseIntercept/HttpRequest.vb, vbnet/AjaxResponseIntercept/My Project/AssemblyInfo.vb, vbnet/AjaxResponseIntercept/Program.vb, vbnet/AjaxResponseIntercept/packages.config, vbnet/DotNetBrowser.Examples.sln
Add an example that demonstrates how to intercept responses to the AJAX requests.
=> Add AjaxResponseIntercept example

README.md, csharp/DotNetBrowser.Examples.sln, csharp/Notifications.InterceptData/App.config, csharp/Notifications.InterceptData/Notifications.InterceptData.csproj, csharp/Notifications.InterceptData/Program.cs, csharp/Notifications.InterceptData/Properties/AssemblyInfo.cs, csharp/Notifications.InterceptData/packages.config, vbnet/DotNetBrowser.Examples.sln, vbnet/Notifications.InterceptData/App.config, vbnet/Notifications.InterceptData/My Project/AssemblyInfo.vb, vbnet/Notifications.InterceptData/Notifications.InterceptData.vbproj, vbnet/Notifications.InterceptData/Program.vb, vbnet/Notifications.InterceptData/packages.config
This PR adds an example that demonstrates how to intercept a notification on the web page.
=> Intercept notifications data

README.md, csharp/DotNetBrowser.Examples.sln, csharp/Printing.WebPageToPdf/App.config, csharp/Printing.WebPageToPdf/Printing.WebPageToPdf.csproj, csharp/Printing.WebPageToPdf/Program.cs, csharp/Printing.WebPageToPdf/Properties/AssemblyInfo.cs, csharp/Printing.WebPageToPdf/packages.config, vbnet/DotNetBrowser.Examples.sln, vbnet/Printing.WebPageToPdf/App.config, vbnet/Printing.WebPageToPdf/My Project/AssemblyInfo.vb, vbnet/Printing.WebPageToPdf/Printing.WebPageToPdf.vbproj, vbnet/Printing.WebPageToPdf/Program.vb, vbnet/Printing.WebPageToPdf/packages.config
This PR adds an example that demonstrates how to load a web page and print it to PDF programmatically.
=> Printing example

README.md, csharp/DotNetBrowser.Examples.sln, csharp/DownloadPdf/App.config, csharp/DownloadPdf/DownloadPdf.csproj, csharp/DownloadPdf/Program.cs, csharp/DownloadPdf/Properties/AssemblyInfo.cs, csharp/DownloadPdf/packages.config, vbnet/DotNetBrowser.Examples.sln, vbnet/DownloadPdf/App.config, vbnet/DownloadPdf/DownloadPdf.vbproj, vbnet/DownloadPdf/My Project/AssemblyInfo.vb, vbnet/DownloadPdf/Program.vb, vbnet/DownloadPdf/packages.config
Add an example that demonstrates how to download a PDF by its URL.
=> Download pdf example

README.md, csharp/DotNetBrowser.Examples.sln, csharp/ShadowDom/App.config, csharp/ShadowDom/Program.cs, csharp/ShadowDom/Properties/AssemblyInfo.cs, csharp/ShadowDom/ShadowDom.csproj, csharp/ShadowDom/example.html, csharp/ShadowDom/packages.config, vbnet/DotNetBrowser.Examples.sln, vbnet/ShadowDom/App.config, vbnet/ShadowDom/My Project/AssemblyInfo.vb, vbnet/ShadowDom/Program.vb, vbnet/ShadowDom/ShadowDom.vbproj, vbnet/ShadowDom/example.html, vbnet/ShadowDom/packages.config
This PR adds an example that demonstrates how to work with Shadow DOM.
=> Shadow DOM example

csharp/AccessingHttpResponseData/Program.cs, csharp/AjaxCallsFilter/Program.cs, csharp/AjaxResponseIntercept/Program.cs, csharp/CertificateError/Program.cs, csharp/CertificateVerifier/Program.cs, csharp/ContextMenu.WinForms/Form1.cs, csharp/CookieFilter/Program.cs, csharp/Cookies/Program.cs, csharp/Demo.WinForms/MainForm.cs, csharp/Demo.Wpf/BrowserTabs.xaml.cs, csharp/DownloadPdf/Program.cs, csharp/NetworkHandlers/Program.cs, csharp/Notifications.InterceptData/Program.cs, csharp/PostData/Program.cs, csharp/Zoom/Program.cs, vbnet/AccessingHttpResponseData/Program.vb, vbnet/AjaxCallsFilter/Program.vb, vbnet/AjaxResponseIntercept/Program.vb, vbnet/CertificateError/Program.vb, vbnet/CertificateVerifier/Program.vb, vbnet/ContextMenu.WinForms/Form1.vb, vbnet/CookieFilter/Program.vb, vbnet/Cookies/Program.vb, vbnet/DownloadPdf/Program.vb, vbnet/JavaScriptBridge.Promises/Program.vb, vbnet/NetworkHandlers/Program.vb, vbnet/Notifications.InterceptData/Program.vb, vbnet/PostData/Program.vb, vbnet/WebSockets.InterceptData/Program.vb, vbnet/Zoom/Program.vb
This PR  updates obsolete code both in C# and VB.NET examples.
=> Update obsolete code

csharp/ContextMenu.Wpf/MainWindow.xaml.cs, csharp/CustomRequestHandling/Program.cs, csharp/DragAndDrop.Wpf/MainWindow.xaml.cs, csharp/FindText/Program.cs, csharp/KeyboardEventSimulation.WinForms/Form1.cs, vbnet/ContextMenu.Wpf/MainWindow.xaml.vb, vbnet/CustomRequestHandling/Program.vb, vbnet/DragAndDrop.Wpf/MainWindow.xaml, vbnet/DragAndDrop.Wpf/MainWindow.xaml.vb, vbnet/FindText/Program.vb, vbnet/KeyboardEventSimulation.WinForms/Form1.vb
This PR updates layout in a few existing examples and adds a markup of the code snippets.
=> Markup existing examples

csharp/AccessingHttpResponseData/Program.cs, csharp/AjaxCallsFilter/Program.cs, csharp/AjaxResponseIntercept/HttpRequest.cs, csharp/AjaxResponseIntercept/Program.cs, csharp/CertificateError/Program.cs, csharp/CertificateVerifier/Program.cs
This PR removes unnecessary console output and exception handling in the following samples:
AccessingHttpResponseData
AjaxCallFilter
AjaxResponseIntercept
CertificateError
CertificateVerifier
=> Update part of examples written in CSharp

csharp/ComWrapper.WinForms/ComBrowserView.cs, csharp/ComWrapper.WinForms/register.bat
This PR updates the COM wrapper example and adds a registration script to it. I have also updated the log file name to make it unique and avoid collisions.
=> Update log file name to make it unique. Add registration script

csharp/SaveImageFromPage/Program.cs, vbnet/SaveImageFromPage/Program.vb
This PR updates the SaveImageFromPage example to demonstrate the use of the new API.
=> Update SaveImageFromPage example

csharp/Demo.WinForms/Components/TabContents.Designer.cs, csharp/Demo.WinForms/Components/TabContents.cs, csharp/Demo.Wpf/BrowserTab.xaml, csharp/Demo.Wpf/BrowserTab.xaml.cs
Add DevTools to the menu in the demo applications.
=> Update demo applications

.gitignore, csharp/unity3d/DotNetBrowser_Unity/Assets/DnbFps/Scripts/MenuBrowserScript.cs, csharp/unity3d/DotNetBrowser_Unity/Assets/DnbSimple/Scenes/DotNetBrowserScene.unity, csharp/unity3d/DotNetBrowser_Unity/Assets/Editor/dotnetbrowser.license.meta
Fixes the camera position in the simple scene, provides a forgotten namespace, and adds a meta file for the license file.
=> Fix camera position

csharp/winforms/ContextMenu.SpellCheck/Form1.cs, csharp/wpf/ContextMenu.SpellCheck/MainWindow.xaml.cs, vbnet/winforms/ContextMenu.SpellCheck/Form1.vb, vbnet/wpf/ContextMenu.SpellCheck/MainWindow.xaml.vb
This PR adds the necessary code which should be used for choosing a spellcheck language.
=> Improve spellcheck samples

csharp/console/WebSockets.InterceptData/Program.cs, csharp/console/WebSockets.InterceptData/WebSockets.InterceptData.csproj, csharp/console/WebSockets.InterceptData/echo.html, vbnet/console/WebSockets.InterceptData/Program.vb, vbnet/console/WebSockets.InterceptData/WebSockets.InterceptData.vbproj, vbnet/console/WebSockets.InterceptData/echo.html
This PR updates the web page used in the `WebSockets.InterceptData` example.
=> Update WebSocket example
